version: '3.8'

services:
  # Enclave - listens on vsock port 5005
  enclave:
    build:
      context: .
      dockerfile: Dockerfile.enclave.vsock
    privileged: true
    devices:
      - /dev/vsock:/dev/vsock
    environment:
      - USE_TLS=true
      - ENCLAVE_PORT=5005
    networks:
      - enclave-net

  # Host proxy - connects to enclave via vsock
  host:
    build:
      context: .
      dockerfile: Dockerfile.host.vsock
    privileged: true
    devices:
      - /dev/vsock:/dev/vsock
    ports:
      - "443:443"
    environment:
      - BIND_ADDR=0.0.0.0:443
      # In Docker, both containers share the same vsock namespace
      # so we use CID 2 (local) to connect
      - ENCLAVE_CID=2
      - ENCLAVE_PORT=5005
    depends_on:
      - enclave
    networks:
      - enclave-net

networks:
  enclave-net:
    driver: bridge