[package]
name = "host"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1"
tokio = { version = "1", features = ["full"] }
# vsock is optional; TCP fallback supported
vsock = { version = "0.5", optional = true }